### ISSUE TITLE
Github Action Secrets Not Available

### ISSUE THREAD

**Issue by larsdesigns** [Lullabot/drainpipe#116]
I have found that the Github Actions Repository Secrets are not available in the environment for Taskfile.yml. 

(Also the file name should probably be taskFile.yml for camelCase or TaskFile.yml for PascalCase but that is probably for another time). 

When tasks such as ` vendor/lullabot/drainpipe/tasks/pantheon.yml` are executed the secret variables are not available. 

Not Available: 
![Screen Shot 2022-08-22 at 4 48 19 PM](https://user-images.githubusercontent.com/976705/186032307-28772fa7-be37-43a3-b6fa-fe620714cd5f.png)

However, my testing indicates that the secret repository variables are available via env for github workflows such as `.github/workflows/PantheonReviewApps.yml` and `.github/workflows/TestFunctional.yml`. 

Available:
![Screen Shot 2022-08-22 at 4 50 33 PM](https://user-images.githubusercontent.com/976705/186032317-d381deb5-3c4f-4e48-bf63-f8cfa2bc2b28.png)

#### Pull Request https://github.com/Lullabot/drainpipe/pull/118

**Comment by justafish** [comment]
The environment variables available inside the runner aren't those available within the DDEV container. Have you followed this example? https://github.com/Lullabot/drainpipe/blob/main/scaffold/github/workflows/PantheonReviewAppsDDEV.yml

> (Also the file name should probably be taskFile.yml for camelCase or TaskFile.yml for PascalCase but that is probably for another time).
This is the standard for task https://taskfile.dev/usage/

**Comment by larsdesigns** [comment]
The `PantheonReviewAppsDDEV.yml` file has parsing errors: 

![Screen Shot 2022-08-29 at 2 17 41 PM](https://user-images.githubusercontent.com/976705/187291599-8e9ba43e-bce5-414d-88b5-e3b53cac5145.png)

I will fix it up in our other project and create a pull request in this project when I resolve the errors.

**Comment by larsdesigns** [comment]
The actual parsing errors: 

```
╰─ yamllint *
CheckYarnDependencies.yml
  1:81      error    line too long (83 > 80 characters)  (line-length)
  2:1       warning  missing document start "---"  (document-start)
  4:1       warning  truthy value should be one of [false, true]  (truthy)

PantheonDevDeploy.yml
  1:1       warning  missing document start "---"  (document-start)
  3:1       warning  truthy value should be one of [false, true]  (truthy)
  46:27     error    too many spaces after colon  (colons)
  73:81     error    line too long (81 > 80 characters)  (line-length)

PantheonProductionDeploy.yml
  1:1       warning  missing document start "---"  (document-start)
  3:1       warning  truthy value should be one of [false, true]  (truthy)
  36:81     error    line too long (96 > 80 characters)  (line-length)

PantheonReviewApps.yml
  1:1       warning  missing document start "---"  (document-start)
  3:1       warning  truthy value should be one of [false, true]  (truthy)

PantheonTestDeploy.yml
  1:1       warning  missing document start "---"  (document-start)
  3:1       warning  truthy value should be one of [false, true]  (truthy)
  43:81     error    line too long (96 > 80 characters)  (line-length)
  53:27     error    too many spaces after colon  (colons)

TestFunctional.yml
  1:1       warning  missing document start "---"  (document-start)
  3:1       warning  truthy value should be one of [false, true]  (truthy)

TestStatic.yml
  1:1       warning  missing document start "---"  (document-start)
  3:1       warning  truthy value should be one of [false, true]  (truthy)
```

**Comment by larsdesigns** [comment]
Opened pull request: https://github.com/Lullabot/drainpipe/pull/118 and committed the fix for the yaml syntax. 

I will go ahead and fix the errors found in the other yml documents.

**Comment by larsdesigns** [comment]
No further tasks. This is ready for review.

**Comment by justafish** [comment]
Thanks!

**Comment by larsdesigns** [comment]
After further testing the the env variables are still not available. I am re-opening until we can resolve the error as depicted in the first screenshot.

**Comment by larsdesigns** [comment]
Here is a link to the full build log: https://gist.github.com/larsdesigns/ef0a08f31fd5449403f4c9c53ddaae1c

We find that on line 21 the `PANTHEON_TOKEN` has a value. However, later in the build process on line [1645](https://gist.github.com/larsdesigns/ef0a08f31fd5449403f4c9c53ddaae1c#file-gistfile1-txt-L1645) the PANTHEON_TOKEN variable is empty. 

I have not been able to determine why this is happening.

@justafish,  Would you have any ideas?

**Comment by justafish** [comment]
I've resolved this with @larsdesigns directly - not an issue with Drainpipe

**Comment by larsdesigns** [comment]
I have developed a fix for this. I am re-opening and will submit a PR.
