### ISSUE TITLE
"failed to open stream: Text file busy" while upgrading Task binary

### ISSUE THREAD

**Issue by hawkeyetwolf** [Lullabot/drainpipe#164]
## How
I got the error while upgrading drainpipe from 1.2.16 to 1.3.0, which included an update to the Task binary (https://github.com/Lullabot/drainpipe/pull/158).

## Why
In `vendor/lullabot/drainpipe/src/BinaryInstaller.php` we reduce the likelihood of seeing the "Text file busy" error by only copying it over when necessary. But when upgrading the Task binary, the file must still be replaced, creating an opportunity for the error to arise.

## Ideas
@deviantintegral mentioned:
> perhaps this circular dependency between task and composer should be broken. Drainpipe could validate the task version, but not actually download it (just as you have to download composer out of band to use it).

Thoughts??

**Comment by hawkeyetwolf** [comment]
cc @justafish

**Comment by deviantintegral** [comment]
I found a similar issue with a race condition when multiple composer commands are running at once using the same composer cache directory.

We got the following error:

```
Using cached version of task v3.21.0 (7232508b0040398b3dcce5d92dfe05f65723680eab2017f3cee6c0a7cf9dd6c1)

In BinaryInstaller.php line 214:
                                                                               
  phar "/var/www/.composer/cache/files/lullabot/drainpipe/bin/task/3.21.0/tas  
  k_linux_amd64.tar" exists and must be unlinked prior to conversion           
                                                                               
```

This error is from the call to `decompress()`:

```
        if ('.tar.gz' === substr($fileName, -7)) {
            $archive = new \PharData($cacheDestination);
            $archive->decompress();
```

If two composer commands are running at the same time, they one may fail if the tar file still exists from the other process.

Two parts I validated:

1. We _always_ decompress the archive, even if the files already exist.
2. This is certainly a race condition that only happens rarely. However, we can replicate this by touching an empty file, as if the computer crashed or PHP was killed.

```
$ touch /mnt/ddev-global-cache/composer/files/lullabot/drainpipe/bin/task/3.21.0/task_linux_amd64.tar

$ composer install
Gathering patches for root package.
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Nothing to install, update or remove
Package doctrine/reflection is abandoned, you should avoid using it. Use roave/better-reflection instead.
Package symfony/debug is abandoned, you should avoid using it. Use symfony/error-handler instead.
Generating autoload files
89 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
Using cached version of task v3.21.0 (7232508b0040398b3dcce5d92dfe05f65723680eab2017f3cee6c0a7cf9dd6c1)

In BinaryInstaller.php line 214:

  phar "/mnt/ddev-global-cache/composer/files/lullabot/drainpipe/bin/task/3.21.0/task_linux_amd64.tar" exists and must be unlinked prior to conversion


install [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--dry-run] [--download-only] [--dev] [--no-suggest] [--no-dev] [--no-autoloader] [--no-progress] [--no-install] [--audit] [--audit-format AUDIT-FORMAT] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--] [<packages>...]
```

**Comment by baluv3** [comment]
Noting here that we think this issue will be resolved, when https://github.com/Lullabot/drainpipe/issues/172 is completed.

**Comment by mrdavidburns** [comment]
Just ran into this error on another project. 
Using drainpipe and drainpipe-dev v3.1.2
