### ISSUE TITLE
Improve or reconsider including task via composer

### ISSUE THREAD

**Issue by deviantintegral** [Lullabot/drainpipe#172]
Requiring task via composer means that when you want to run tasks that don't actually need composer you have to bootstrap it. Off the top of my head:

- deploy:git
- deploy:archive
- terminus

all may not need composer. As well, when bootstrapping a new clone, you may have tasks that run composer install, but you have to run `composer install` before you can do something like `task build:dev` or `task composer:install`.

I think for ddev projects, it makes sense to install task via the Dockerfile, just like how composer or terminus is. However, there isn't an _easy_ way to ensure the right version is installed to match drainpipe.

Ideas:

- Task for linux is only 5MB. We could treat it as a scaffold file, and then it's always available from the start?
  - If we do this, we'd have to commit and manage all OS and arch combinations. However, that looks to be somewhat broken right now, because in my arm container I'm getting an amd64 task binary.
- Make an easy way to identify what version of task drainpipe wants, without having to run PHP. Then a dockerfile could pull the right version down? The downside being is it requires a container restart to update, unless we make sure to overwrite the same location in vendor/bin/*.

**Comment by justafish** [comment]
@deviantintegral if we could keep the versions in sync is there any downside to having both available? i.e. the composer installed version as well as a global one for ddev

**Comment by deviantintegral** [comment]
I don't think so. The hard part is "keep the versions in sync".

Is there a way we can include the task version in the `composer.lock` file? Then we could use `jq` to install task in `vendor/bin` without bootstrapping composer.

**Comment by mrdavidburns** [comment]
Would including task via composer resolve these errors?

```
Checking for latest local-php-security-checker releases ...
Downloading local-php-security-checker_2.0.6_linux_386...
Symlinking local-php-security-checker_2.0.6_linux_386 as local-php-security-checker in composer bin-dir.
Creating initial Taskfile.yml...
Creating initial .gitignore...

In ScaffoldInstallerPlugin.php line 179:

  file_get_contents(composer.json): Failed to open stream: No such file or directory


install [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--dry-run] [--download-only] [--dev] [--no-suggest] [--no-dev] [--no-autoloader] [--no-progress] [--no-install] [--audit] [--audit-format AUDIT-FORMAT] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--] [<packages>...]

composer [install --no-interaction --no-cache] failed, composer command failed: exit status 1. stderr=


~ ddev composer install 

Gathering patches for root package.
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Nothing to install, update or remove
Package doctrine/reflection is abandoned, you should avoid using it. Use roave/better-reflection instead.
Package swiftmailer/swiftmailer is abandoned, you should avoid using it. Use symfony/mailer instead.
Package symfony/debug is abandoned, you should avoid using it. Use symfony/error-handler instead.
Generating autoload files
90 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
PHP CodeSniffer Config installed_paths set to ../../drupal/coder/coder_sniffer,../../sirbrillig/phpcs-variable-analysis,../../slevomat/coding-standard

In Filesystem.php line 254:

  /dev/null/files/lullabot/drainpipe/bin/task/3.18.0 does not exist and could not be created.


install [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--dry-run] [--download-only] [--dev] [--no-suggest] [--no-dev] [--no-autoloader] [--no-progress] [--no-install] [--audit] [--audit-format AUDIT-FORMAT] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--] [<packages>...]

composer [install --no-interaction --no-cache] failed, composer command failed: exit status 1. stderr=
```

**Comment by deviantintegral** [comment]
I think including task via composer (as we currently do) is _causing_ these errors.

Given we are very much tied to ddev in drainpipe, I think it would make sense for us to add a `Dockerfile.task` file to the web directory that downloads task to `/usr/local/bin/`. The biggest downside is that changes wouldn't apply until you restarted ddev. However, I think that we could change the composer side to simply _validate_ the right version of task is available without making any filesystem changes.

**Comment by davereid** [comment]
+1 for including _necessary_ command binaries via Dockerfile, I've found it the most reliable way and they're ready to use as soon as DDEV starts without composer.
