### ISSUE TITLE
Ensure Mutagen is Disabled

### ISSUE THREAD

**Issue by quicksketch** [Lullabot/drainpipe#173]
Lullabot Support and Maintenance has started enabling Mutagen by default in their projects' `.ddev/config.yml` files, since most of the team is running on MacOS and get a benefit from it.

Having mutagen on by default has the side-effect of installing Mutagen inside of GitHub Actions when using Drainpipe. That adds an unnecessary install, an initial filesystem syncing time, and the potential for filesystem weirdness. I think it would be a good idea to ensure Mutagen is disabled, overriding the default setting from the repository.

**Comment by deviantintegral** [comment]
Randy has explicitly recommended against enabling mutagen per project in discord discussions. Needing mutagen is very much dependent on how the host is set up. The docs at https://ddev.readthedocs.io/en/stable/users/install/performance/#mutagen say to run `ddev config global --mutagen-enabled`.

I think the proper fix is for LSM to not configure this per project. Thoughts @mrdavidburns @YesCT ?

**Comment by YesCT** [comment]
I dont feel strongly. I think we started down a path, and stuck with it, till we ran into a reason to change. Seems like we are running into that now. I'm open to the other way around and using whatever is a more common recommended setup.

I find the benefit of having mutagen off by default for CI type things to make a lot of sense to me. I think originally we were viewing it more as local dev only.

**Comment by justafish** [comment]
I agree with @deviantintegral's comment, so closing this out for now :+1:
