### ISSUE TITLE
.env file in projects is overwritten by scaffolding

### ISSUE THREAD

**Issue by deviantintegral** [Lullabot/drainpipe#183]
We noticed that on locals that _sometimes_ the .env file would reset to defaults. Developers are storing API keys and credentials in that file, which means it would break their locals.

https://github.com/Lullabot/drainpipe/blob/main/composer.json#L28-L34

Shouldn't this only copy the file if it doesn't exist?

To reproduce:

1. Run composer install.
2. Edit `.env`.
3. Run composer install.
4. Note your changes are gone and you will see:

```
Scaffolding files for lullabot/drainpipe:
  - Copy [project-root]/.env from scaffold/env/env
```

As a workaround, projects can set that scaffold file to `false` in their root composer.json.

**Comment by justafish** [comment]
Fixed in #202
