### ISSUE TITLE
Confirm sass:watch is working and fix if needed

### ISSUE THREAD

**Issue by deviantintegral** [Lullabot/drainpipe#193]
`sass:watch` is not working for us on at least one client project. It works the first time, but then subsequent changes don't get picked up. We think the problem is somewhere in the gulpfile.

Talk to @mtift about this one for details!

**Comment by pjudge** [comment]
@mtift Thanks for pointing me to the slack discussion. I'm actually able to reproduce this! Looking into it.

**Comment by pjudge** [comment]
Updating here to say I'm still working on this. I have reproduced this with a local fresh install of D9, the UMass project, and ABA. The strange thing is that it did initially work on my fresh D9, but after trying UMass, the bug showed up in both. Going to spend some time trying more things.
