### ISSUE TITLE
Replace phpcs.xml scaffold with phpcs.xml.dist

### ISSUE THREAD

**Issue by justafish** [Lullabot/drainpipe#238]
Overrides would then be done in `phpcs.xml` with the following:
```
 <rule ref="phpcs.xml.dist">
  </rule>
```

**Comment by deviantintegral** [comment]
I'm calling this a bug because the current implementation is the opposite to what phpcs expects by default, and that's pretty confusing for new users!

**Comment by geekygnr** [comment]
Got the details I was looking for. I updated the README to point to the documentation I over looked to improve its visibility.

**Comment by davereid** [comment]
@geekygnr Is there a PR open for this? I only see your commit but not a PR.

**Comment by geekygnr** [comment]
> @geekygnr Is there a PR open for this? I only see your commit but not a PR.

I did not. It is now made.
