### ISSUE TITLE
Change GitHub Actions workflow job runners from ubuntu-latest to ubuntu-22.04

### ISSUE THREAD

**Issue by hawkeyetwolf** [Lullabot/drainpipe#256]
On another project, we recently switched from `ubuntu-latest` to `ubuntu-22.04` for all our GitHub Actions workflow runners, for stability. And I noticed that Drainpipe was overwriting the ComposerLockDiff workflow with `ubuntu-latest`. Do we want to change that here too, or no?

cc @deviantintegral

**Comment by justafish** [comment]
Do you mean so that the version doesn't change unexpectedly one day?
According to https://github.com/actions/runner-images#available-images `ubuntu-latest` is `ubuntu-22.04`

**Comment by deviantintegral** [comment]
Exactly. Latest used to be 20.04 until they bumped it.

**Comment by justafish** [comment]
sounds like a good idea! :+1:
