### ISSUE TITLE
ComposerLockDiff fails when PR description contains "#\"

### ISSUE THREAD

**Issue by hawkeyetwolf** [Lullabot/drainpipe#257]
The ComposerLockDiff GitHub Actions workflow fails on PRs that have "#\\" in the PR description. 

In my case, I was trying to print "<span>#</span>2" without GitHub automatically linking to the corresponding issue or PR number 2. So I added a slash in front like this: "#\2", and then the ComposerLockDiff workflow began failing. Changing the PR description to `<span>#</span>2` made the workflow begin passing again.

This issue is very similar to [#181 (closed): Error in composer-lock diff process when PR description contains new lines](https://github.com/Lullabot/drainpipe/issues/181). The error is the same:

    curl: (22) The requested URL returned error: 400
    Error: Process completed with exit code 22.

which happens when executing line 52 in the workflow file:
https://github.com/Lullabot/drainpipe/blob/272d2415fc5e8cd08e5dd76ff84ab1372d4ab974/scaffold/github/workflows/ComposerLockDiff.yml#L52

**Comment by hawkeyetwolf** [comment]
cc @deviantintegral

**Comment by penyaskito** [comment]
I have a similar issue in https://github.com/IowaWeb/iowadt/pull/1745, but not with `#\`. In this case I suspect is a code block with an iframe.

**Comment by deviantintegral** [comment]
There's also an issue causing it to remove `\`. See in this diff how `\\xd2` became `\xd2`:

<img width="499" alt="image" src="https://github.com/Lullabot/drainpipe/assets/255023/8d9208d6-258e-4e6e-b0e8-3b8ded01d8d9">

**Comment by deviantintegral** [comment]
Related: #332 .

**Comment by mrdavidburns** [comment]
Is #318 also related?

**Comment by deviantintegral** [comment]
It wouldn't surprise me if it's the same section of code causing the problem, but we won't know until someone dives into this.
