### ISSUE TITLE
Version of Terminus used in Gitlab integration is very old

### ISSUE THREAD

**Issue by ABAJosh** [Lullabot/drainpipe#258]
Drainpipe currently uses Terminus 3.0.7, while the current version is 3.2.1. We should upgrade to the current version. This is a simple change in the following file: `scaffold/gitlab/Pantheon.gitlab-ci.yml`

The line:
 `curl -L https://github.com/pantheon-systems/terminus/releases/download/3.0.7/terminus.phar --output ~/terminus/terminus`

should be changed to:
`curl -L https://github.com/pantheon-systems/terminus/releases/download/3.2.1/terminus.phar --output ~/terminus/terminus`

**Comment by justafish** [comment]
@ABAJosh :wave: Could you test this branch on your site and check that it doesn't break anything please? I don't have anything with GitLab setup to hand at the moment [259](https://github.com/Lullabot/drainpipe/pull/259)

**Comment by ABAJosh** [comment]
Tested and verified that Terminus is working as expected.
