### ISSUE TITLE
Fix coding standards error in settings.tugboat.php

### ISSUE THREAD

**Issue by mrdavidburns** [Lullabot/drainpipe#287]
This error started to appear when Renovate created a PR to upgrade to Drainpipe(-dev) v3.2.0
```
[test:phpcs] FILE: /var/www/html/web/sites/default/settings.tugboat.php
[test:phpcs] ----------------------------------------------------------------------
[test:phpcs] FOUND 1 ERROR AND 1 WARNING AFFECTING 1 LINE
[test:phpcs] ----------------------------------------------------------------------
[test:phpcs]  31 | WARNING | [ ] Line exceeds 80 characters; contains 83
[test:phpcs]     |         |     characters
[test:phpcs]  31 | ERROR   | [x] Perl-style comments are not allowed; use "//
[test:phpcs]     |         |     Comment" instead
[test:phpcs] ----------------------------------------------------------------------
[test:phpcs] PHPCBF CAN FIX THE 1 MARKED SNIFF VIOLATIONS AUTOMATICALLY
[test:phpcs] ----------------------------------------------------------------------
```

**Comment by mrdavidburns** [comment]
@justafish I'm curious as to why we have `scaffold/tugboat/settings.tugboat.php.twig` while we have `scaffold/pantheon/settings.pantheon.php`.

Should we rename `settings.tugboat.php.twig` to `settings.tugboat.php` and address the syntax error in this file?

**Comment by justafish** [comment]
@mrdavidburns the settings file generated for Tugboat is a bit more complex - it takes it's PHP and database version from DDEV, whereas the pantheon settings is a fixed file. It'd be nice in future if this would take values from DDEV too and populate pantheon.yml :grin:
