### ISSUE TITLE
ComposerLockDiff changes line endings, breaking editing PR descriptions in GitHub

### ISSUE THREAD

**Issue by deviantintegral** [Lullabot/drainpipe#318]
When editing pull request descriptions, ComposerLockDiff changes `\r\n` to `\n\n`. This makes it very difficult to edit the PR description in the UI, because you have hidden unprintable characters. Top is before (`pull_request.json`), bottom is after (`processed.json`):

<img width="412" alt="image" src="https://github.com/Lullabot/drainpipe/assets/255023/929d60d4-1578-44ca-b905-7f2988956033">

This would be partially solved by #317 moving the contents to a comment, but should also be fixed because `\n` is not supported: https://stackoverflow.com/a/46751663 (most web applications use `\r\n` for line endings): https://www.rfc-editor.org/rfc/rfc7230#section-3.5

**Comment by justafish** [comment]
Closing in favour of #332

**Comment by beto-aveiga** [comment]
If we are going to do this, I can work on a PR to fix the `\n\n \r\n` issue.
@deviantintegral @justafish

**Comment by YesCT** [comment]
@beto-aveiga I'm not sure, but I think you might want to build on the branch from https://github.com/Lullabot/drainpipe/pull/538 . Unless @davereid is also going to work on the line ending thing in his PR.

**Comment by davereid** [comment]
My fix is to move the composer lock diff to a sticky PR comment instead of updating the PR description. The work for this would be fixed by https://github.com/Lullabot/drainpipe/pull/538

**Comment by davereid** [comment]
But we could put in a fix *now* since that's needing some more detailed time and reviews. Ultimately the fix would be deprecated/removed by the work in #538.

**Comment by mrdavidburns** [comment]
Going to move this into Blocked until we move this task out of DDEV.
Complete #283 first

**Comment by justafish** [comment]
Fixed in #636
