### ISSUE TITLE
Generate Environment Indicator settings

### ISSUE THREAD

**Issue by deviantintegral** [Lullabot/drainpipe#369]
Let's investigate automatically adding environment indicator settings, since we use it on all projects: https://architecture.lullabot.com/adr/20210609-environment-indicator/

**Comment by geekygnr** [comment]
I am confused by this ticket:

My first instinct was something like this was needed: https://github.com/Lullabot/drainpipe/blob/main/scaffold/tugboat/settings.tugboat.php.twig#L32

But it exists already.

I am confirming function now.

**Comment by geekygnr** [comment]
I tested against a bare bones Drupal set up with environment indicator enabled. It seems to function as required on tugboat.

I am going to see if this is/can be set up for other environments

**Comment by geekygnr** [comment]
Pantheon seems to have a similar set up: https://github.com/Lullabot/drainpipe/blob/main/scaffold/pantheon/settings.pantheon.php#L94

**Comment by geekygnr** [comment]
Created something to automatically configure ddev.
