### ISSUE TITLE
Upgrade actions/upload-artifact and actions/download-artifact actions to v4

### ISSUE THREAD

**Issue by justafish** [Lullabot/drainpipe#385]
Renovate opened some PRs for this (https://github.com/Lullabot/drainpipe/pull/432), but the tests are broken

https://github.com/Lullabot/drainpipe/pull/378
https://github.com/Lullabot/drainpipe/pull/377

**Comment by dsayswhat** [comment]
Per discussion with @justafish: @penyaskito to look at merge multiple to avoid errors when uploading artifacts
