### ISSUE TITLE
Add config overrides support for Tugboat

### ISSUE THREAD

**Issue by justafish** [Lullabot/drainpipe#388]
Add support for a `config-overrides.yml` file that will merge with the auto-generated `config.yml` file to allow things like service aliases and visual diff support. Initially this should only support

- `aliases`
- `urls`
- `screenshot`
- `visualdiff`

and ignore everything else.

**Comment by tess-ten7** [comment]
This would be so, so useful for us.

**Comment by KeyboardCowboy** [comment]
@justafish or @deviantintegral, the `ScaffoldInstallerPlugin.php` file has a lot going on in it, namely the `installCICommands()` method.  Would it be OK if I split the Tugboat processing into its ScaffoldService class if I'm going to add additional processing for the overrides file?

**Comment by KeyboardCowboy** [comment]
I spun up a test/example repo to test these changes.  Checking out this branch and running `composer install` should produce the desired `config.yml`.

https://github.com/Lullabot/drainpipe-test/tree/388--config-overrides-tugboat
