### ISSUE TITLE
Make Taskfile includes optional by default

### ISSUE THREAD

**Issue by deviantintegral** [Lullabot/drainpipe#393]
We went to the effort a few years back to support optional taskfile includes in Task: https://github.com/go-task/task/issues/519

However, our default taskfile has all of the files as required!

https://github.com/Lullabot/drainpipe/blob/ee7ef635c34f6c27e3f375f9b79f923f593ea389/scaffold/Taskfile.yml#L5-L12

If we change this, it will allow new developers to bootstrap a site without needing to run `composer install` first. I've prototyped this on a customer site, and we have new setup steps down to exactly two commands:

`ddev start && ddev task build:dev:install`

The install command has a dependency on a composer install task as I noted at https://github.com/Lullabot/drainpipe/issues/191.

**Comment by deviantintegral** [comment]
I'm calling this a bug for now, because I think we always intended these to be optional once upstream supported it.

**Comment by justafish** [comment]
just for historical context - these weren't intended to be optional, it was added because the test task was in a different composer package that wouldn't necessarily be present if you'd installed just the production dependencies

**Comment by justafish** [comment]
Closing this as composer install needs to run to bring in task
