### ISSUE TITLE
Add config to automate unblocking user 1

### ISSUE THREAD

**Issue by YesCT** [Lullabot/drainpipe#394]
To make it easier to follow ADR: https://architecture.lullabot.com/adr/20211026-one-time-login-first-drupal-user-account/

Add a config that will also unblock user 1 during the builds for locals and tugboat.

**Comment by justafish** [comment]
I don't think there's anything really we can add here as it's already a one-liner and we're not prescriptive about how you build your site, but I have added it as an example to the initial Taskfile scaffold #418
