### ISSUE TITLE
Add a CI hook to delete old Pantheon multidev environments

### ISSUE THREAD

**Issue by deviantintegral** [Lullabot/drainpipe#408]
AFAIK, we don't manually touch multidev environments built by PRs in this repo. We've seen PRs fail due to hitting Pantheon's environment limit.

What if we added a scheduled action that deleted multidevs older than 1 day? Then even if we hit the limit, it should eventually clean up and get PRs back to passing.

**Comment by justafish** [comment]
Sounds like a good idea - a day is probably a bit too short though. Maybe 10 days?

I do go into the dashboard and manually shut stale environments down if they've been open for a while to open some slots

**Comment by deviantintegral** [comment]
I'm marking this as both high and a bug, since it keeps coming up blocking unrelated PRs.

**Comment by davereid** [comment]
Do we have an action that automatically deletes the multidev environment/deployment when the PR is closed/merged?

**Comment by mrdavidburns** [comment]
I believe this happens every time a MultiDev environment is created or updated.
https://github.com/Lullabot/drainpipe/blob/main/scaffold/github/actions/pantheon/review/action.yml#L52

**Comment by justafish** [comment]
We have 20 environments now :tada:
