### ISSUE TITLE
Switch from a GitHub Token to a deploy key

### ISSUE THREAD

**Issue by justafish** [Lullabot/drainpipe#460]
these don't expire and aren't tied to a user :tada:

**Comment by deviantintegral** [comment]
It sounds like this would have prevented https://github.com/Lullabot/drainpipe/issues/428 from happening.

**Comment by davereid** [comment]
Yup. I'm taking this on to try and help fix this for the near future. I created a deploy key for drainpipe-dev and added the private key part as a secret to drainpipe repository. Now working on updating https://github.com/Lullabot/drainpipe/blob/main/.github/workflows/DrainpipeDev.yml
