### ISSUE TITLE
Change some values from secrets to variables, for example PANTHEON_SITE_NAME

### ISSUE THREAD

**Issue by YesCT** [Lullabot/drainpipe#463]
https://github.com/Lullabot/drainpipe?tab=readme-ov-file#pantheon

Change some values from secrets to variables

PANTHEON_SITE_NAME seems a candidate for a variable. Are there any reasons to have it be a secret?

TERMINUS_PLUGINS also?

any others?

<img width="858" alt="Screenshot 2024-03-04 at 2 00 42 PM" src="https://github.com/Lullabot/drainpipe/assets/1970586/58a8727e-7bb8-436a-aace-a4ea489653e8">

**Comment by YesCT** [comment]
Having a variable allows inspecting it's value. Easier for debugging.

**Comment by davereid** [comment]
+1 for using a variable for PANTHEON_SITE_NAME since it's not a secret. I also have some code I could use from a prior project that makes setting that very optional based on reading from the Github repository name or the DDEV config file.

**Comment by justafish** [comment]
https://github.com/Lullabot/drainpipe/blob/main/scaffold/github/workflows/PantheonReviewAppsDDEV.yml#L45
apparently we can change this to e.g. `${{ vars.secrets.PANTHEON_SITE_NAME || secrets.PANTHEON_SITE_NAME }}`
