### ISSUE TITLE
PHP 8.2 needs `default-mysql-client` instead of `mysql-client`

### ISSUE THREAD

**Issue by mrdavidburns** [Lullabot/drainpipe#473]
On a project that is not on Acquia or Pantheon we're running into an issue trying to upgrade to PHP 8.2.

This is the error we're seeing.
```
E: Package 'mysql-client' has no installation candidate
```

[This stackoverflow thread](https://stackoverflow.com/a/57489274/23561476) suggests the package we need to use is named `default-mysql-client` instead of `mysql-client`.

**Comment by geekygnr** [comment]
I built a bare bones drupal set up with php 8.2 and am not seeing an issue.

![image](https://github.com/Lullabot/drainpipe/assets/5747760/0ce2cb35-104c-48ee-a8b6-228dce0d33c9)

Is there some part of this I am missing?

**Comment by geekygnr** [comment]
I was slow yesterday, I found the error after switching the db config to mysql.
