### ISSUE TITLE
Evaluate and define a common pattern and standard for release versioning

### ISSUE THREAD

**Issue by deviantintegral** [Lullabot/drainpipe#5]
The three patterns I'm aware of are:

- Semantic versioning
- date-based (like `YYYY.MM.DD--#`)
- Float based (`1`, `2.1`, `3`) like how browsers do it
- commit hash (`main-deadbeef`), though this may need an incrementing integer too to represent multiple builds of the same commit

Drupal sites typically don't make any sort of API commitment, and in fact many sites don't bother with versions at all. However, for builds, it's useful to always have a unique ID. Let's determine a best practice so we can rely on it for automation.

**Comment by justafish** [comment]
I don't think this is something we should be prescriptive about, there's all sorts of options here depending on how a team likes to do it's release schedule. Off the top of my head, I've worked on sites that used semantic versioning (because it was decoupled and did have an API commitment), date based, and sprint name. The only common thing amongst them is it being based on a tag.

**Comment by deviantintegral** [comment]
In some ways, it seems like "sprint name" could be managed via dates as well. I think this is one of those cases where having good defaults would cover most cases.

From a tag standpoint, the typical requirements I have are:

1. Given a tag, I can reasonably infer when it was deployed.
2. All tags are in the same format, so I never get confused between `MM` and `DD`, or so I can parse them later. Obviously this doesn't always work with existing code bases.
3. Support for multiple tags in a day, via an integer or timestamp.

What if we _recommend_ the following:

- By default, projects should use dates for tags.
  - For dates, we use `YYYY-MM-DD--#` because it's at least somewhat ISO-y.
- For projects making API commitments, use semver.
- Other tag formats are _possible_ but not _recommended_.

Tooling:

- If a tag isn't specified when creating a release, we default to generating a date tag.
- Specifying a tag by hand is always allowed, with no restrictions, but is optional.

**Comment by deviantintegral** [comment]
I'm closing this as if anything, I think we'd start with an ADR and then consider if implementing that in Drainpipe makes sense.
