### ISSUE TITLE
drupal:import-db and drupal:export-db don't compress data, though they use .sql.gz filenames

### ISSUE THREAD

**Issue by deviantintegral** [Lullabot/drainpipe#519]
There's two related bugs that make imports and exports work, but in a confusing way.

First, the `export-db` command doesn't compress the database, but it saves it to `db.sql.gz`:

https://github.com/Lullabot/drainpipe/blob/47fb6f07df623cd0e29ee5cc1ccf45860f3c98d7/tasks/drupal.yml#L55

We need to either name the file to `.sql`, or do something like pass `--gzip`.

Likewise, the `import-db` command takes a `.sql.gz` file, but doesn't decompress it. So, if other code creates an expected compressed file, it will fail.

https://github.com/Lullabot/drainpipe/blob/47fb6f07df623cd0e29ee5cc1ccf45860f3c98d7/tasks/drupal.yml#L47

Normally, I'd suggest that we should use a more modern compression program, but both Acquia and Pantheon download in gzip format, and having mixed compression formats would be tricky for devs to manage.

**Comment by mrdavidburns** [comment]
@alexanderpatriciop See if `pigz` will work w/ Drainpipe for compressed databases. If so update the pull request. If not, leave a comment on the pull request and then pass it over to me for review.
