### ISSUE TITLE
Test Tugboat workflow is always failing due to DDEV installing newer database version

### ISSUE THREAD

**Issue by davereid** [Lullabot/drainpipe#539]
https://github.com/Lullabot/drainpipe/actions/workflows/TestTugboat.yml is always failing now because DDEV is being installed and started without configuring the database version before the first start:

```
Run ddev config --auto
You are reconfiguring the project at /home/runner/work/drainpipe/drainpipe.
The existing configuration will be updated and replaced.
Configuring a 'drupal' project with docroot 'web' at /home/runner/work/drainpipe/drainpipe/web
Configuration complete. You may now run 'ddev start'.
You are reconfiguring the project at /home/runner/work/drainpipe/drainpipe.
The existing configuration will be updated and replaced.
Configuring a 'drupal' project with docroot 'web' at /home/runner/work/drainpipe/drainpipe/web
Configuration complete. You may now run 'ddev start'.
You are reconfiguring the project at /home/runner/work/drainpipe/drainpipe.
The existing configuration will be updated and replaced.
Configuring a 'drupal' project with docroot 'web' at /home/runner/work/drainpipe/drainpipe/web
Configuration complete. You may now run 'ddev start'.
You are reconfiguring the project at /home/runner/work/drainpipe/drainpipe.
The existing configuration will be updated and replaced.
Configuring a 'drupal' project with docroot 'web' at /home/runner/work/drainpipe/drainpipe/web
unable to configure project drainpipe with database type mariadb:10.11 because that database type does not match the current actual database. Please change your database type back to mariadb:10.11 and start again, export, delete, and then change configuration and start. To get back to existing type use 'ddev config --database=mariadb:10.11', and you can try a migration with 'ddev debug migrate-database mariadb:10.4' see docs at https://ddev.readthedocs.io/en/stable/users/extend/database-types/
```

## Why does it happen
* Install DDEV and starts, which installs MariaDB 10.11
* We then run the folllowing:
  ```
  ddev config --auto
  ddev config --php-version "8.1"
  ddev config --nodejs-version "18"
  ddev config --database=mariadb:10.4
  ```
* You can't downgrade the DDEV database version after the mariadb container has been initialized

## Potential Solutions
1. Should we set these configurations first before the first DDEV start?
2. Should we just update our `--database=mariadb:10.11`? Should we be using these old versions of PHP and NodeJS?
3. Should we just run a ddev destroy and then re-configure? This seems like it would be slower.
4. Could we switch to using https://github.com/ddev/github-action-setup-ddev which provides an option to not start DDEV so it can be configured before first start?

**Comment by justafish** [comment]
@davereid there's a fix for it in https://github.com/Lullabot/drainpipe/pull/533 that we can separate out

**Comment by justafish** [comment]
@davereid I've pulled out the above (which is option #2) in your list, but please re-open if you think we should pick a different solution :smile_cat:
