### ISSUE TITLE
Taskfile scaffold won't generate a working tugboat preview

### ISSUE THREAD

**Issue by geekygnr** [Lullabot/drainpipe#549]
The taskfile scaffold has a sync task that by default runs `drush site:install` but the update task relies on the `drupal:update` task which does a config import.

The config import will always throw an error because the config is either not present or belonging to a different site.

Fixing this so the scaffold can build a functioning tugboat out of the box could help test drainpipe/tugboat integration and could also help new adopters of the project learn the integration.

I am still debating on what the proposed solution should be.

**Comment by geekygnr** [comment]
So far the only solution I can think of is something along the lines of:

diff --git a/tasks/drupal.yml b/tasks/drupal.yml
index 77faa95..736738b 100644
--- a/tasks/drupal.yml
+++ b/tasks/drupal.yml
@@ -63,7 +63,10 @@ tasks:
       # a dependency correctly. This is also useful when importing large config sets
       # as it can sometimes hit an out of memory error.
       - ./vendor/bin/drush {{.site}} --yes config:import || true
-      - ./vendor/bin/drush {{.site}} --yes config:import
+      - |
+        if [[ $(./vendor/bin/drush {{.site}} config:status --format=json --state=Different) != '[]' ]]; then
+          ./vendor/bin/drush {{.site}} --yes config:import
+        fi
       - ./vendor/bin/drush {{.site}} --yes cache:rebuild
       - ./vendor/bin/drush {{.site}} --yes deploy:hook
       - |

Still weighing the potential consequences of a change like this.

**Comment by justafish** [comment]
You could add add an `update:tugboat` task, or run config export after `site:install`, but since the site you're spinning Tugboat up on will need a repository containing Drupal I think it's a reasonable assumption to make that the configuration will be exported by that point, but feel free to re-open if you disagree!
