### ISSUE TITLE
Remove TOC from README

### ISSUE THREAD

**Issue by davereid** [Lullabot/drainpipe#567]
We should have an automated way to catch if the README.md file is updated with new headings, but the automatic [DocToc table of contents](https://github.com/thlorenz/doctoc) hasn't been changed.

Or alternatively, we could have a workflow that automatically adds a commit to the PR that fixes it automatically. https://github.com/marketplace/actions/toc-generator could potentially be used for this, but we would need to provide a GITHUB_TOKEN that is generated using our GitHub app so that workflows will run after the commit.

**Comment by justafish** [comment]
GitHub has got a table of contents built in so maybe we don't need it at all?
![image](https://github.com/Lullabot/drainpipe/assets/345613/de101916-c5cb-49d2-9f1c-b624b844a773)
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-readmes#auto-generated-table-of-contents-for-readme-files

**Comment by deviantintegral** [comment]
Wow, that's totally new, and awesome! I'm fine with that, and teams using GitLab or Bitbucket can make their own decisions.
