### ISSUE TITLE
Add GitHub Action to run `composer outdated` and `composer audit`

### ISSUE THREAD

**Issue by mrdavidburns** [Lullabot/drainpipe#597]
We have noticed on some projects that Renovate is not picking up major version upgrades or we have pinned versions that are not getting new releases. We would like to have a GitHub action that we can run on a weekly or monthly basis so that anyone with access to the logs of that job can identify these packages then we can create tickets to get those packages updated.

**Comment by mrdavidburns** [comment]
@justafish Yes, and we do have that configured for things like Drupal core major and point releases. 
I created this when reviewing all our LSM projects and was running those 2 commands to determine if anything was being missed. It doesn't take long to checkout the latest code and run these commands manually. I was thinking this could be helpful to avoid having to do that step, but agree it probably isn't needed for all projects using Drainpipe.

Closing.

**Comment by YesCT** [comment]
There have been cases where renovate did not alert us. I'll share a slack link in our internal devops channel.
