### ISSUE TITLE
Add 'acquia' tasks include file with 'database' task

### ISSUE THREAD

**Issue by hawkeyetwolf** [Lullabot/drainpipe#60]
_Placeholder issue for linking from client project._

For an example, see the Pantheon integration in [`tasks/pantheon.yml`](https://github.com/Lullabot/drainpipe/blob/main/tasks/pantheon.yml)

**Comment by marcoscano** [comment]
Knowing that Acquia Cloud works well with [remote Drush aliases](https://docs.acquia.com/cloud-platform/manage/ssh/drush/aliases), what would this task contain to provide value to devs?

The `drush sql:sync "$alias" @self.local` command seems to work well for me, and we could combine it with `sql:drop` or `sql:sanitize` depending on project needs, so I'm wondering what this task would be doing that would be too different. I'm probably missing something though :)

**Comment by hawkeyetwolf** [comment]
Hmm, yeah maybe there's not much to extrapolate into a generic Drainpipe task. If it turns out there are a series of steps (like dropping, sanitizing, etc.) we can either make a task for it here, or if it seems very project-specific, just put it in our repo's `Taskfile.yml`.

**Comment by marcoscano** [comment]
👍 For now I've created a ddev command that is more or less like so:

```
# Usage: ddev downsync <sitename>

alias="@$1.prod"
# ... confirm with the user they know what they are doing, and then:
drush @self.local sql:drop --yes
drush sql:sync "$alias" @self.local --yes
drush @self.local sql:sanitize --sanitize-password=admin --yes
# Make sure User 1's username locally is 'admin', since ASF installs sites with another username for UID 1.
drush @self.local php:eval 'Drupal\user\Entity\User::load(1)->set("name", "admin")->save();'
task drupal:update site=@self.local
```

IMO, I don't think this would be a generic solution, since it assumes certain alias patterns, sanitized passwords (and other sanitization parameters), something specific to Acquia Site Factory, etc.

**Comment by deviantintegral** [comment]
lullabot.com calls it's task `sync`, and last week I was totally expecting something like `ddev pull pantheon` to work. There's many ways I could see commands wrapping steps, such as:

1. ddev pull wrapping task wrapping drush
2. task wrapping ddev pull wrapping drush
3. task calling drush directly
4. ddev calling drush directly

(drush would be terminus drush for pantheon sites).

Perhaps we can try to make this more consistent somehow?

**Comment by hawkeyetwolf** [comment]
TIL about `ddev pull` =D What happened when you tried running it on lullabot.com @deviantintegral? It's supposed to [support pantheon[(https://ddev.readthedocs.io/en/stable/users/providers/pantheon/).

Our current project uses Acquia Site Factory, so it would probably require writing a separate ddev provider integration vs. using the standard Acquia Cloud provider integration. The script @marcoscano posted above might be a starting point.

**Comment by deviantintegral** [comment]
@hawkeyetwolf ddev has example templates for hosting providers, but you have to enable them. You'll see them on your local, but one hasn't been set up for lullabot.com (providers directory doesn't exist): https://github.com/Lullabot/lullabot.com-d8/tree/main/.ddev

> Our current project uses Acquia Site Factory, so it would probably require writing a separate ddev provider integration 

I totally think a template for this would be accepted by Randy in ddev.

**Comment by hawkeyetwolf** [comment]
Thank you for checking in on it @deviantintegral. I'm leaning toward this isn't needed. The database download step is probably going to be pretty different per project, and so not easily genericized. E.g., on a recent Acquia project, @marcoscano configured a cron job to export the database, and then we use this script to download it as part of our local refresh script:
```sh
#!/usr/bin/env bash
set -e

REPO_ROOT="$1"
echo "Will use repo root: ${REPO_ROOT}"
DUMP_URL="http://SANITIZED"
DUMP_TIMESTAMP_URL="http://SANITIZED"

# If we can't access the dir passed in, no point in continuing.
cd "${REPO_ROOT}" || exit 42
# Make sure the destination directory exists.
mkdir -p "${REPO_ROOT}/files/private" || true
echo "Starding DB dump download...."
wget "${DUMP_URL}" --output-document="${REPO_ROOT}/files/private/db.sql.gz"
echo "Done downloading DB dump."
echo "Starting DB timestamp download...."
wget "${DUMP_TIMESTAMP_URL}" --output-document="${REPO_ROOT}/files/private/db_generated_date.txt"
echo "Done downloading DB timestamp file."
chmod -R 755 "${REPO_ROOT}/files/private"
```
