### ISSUE TITLE
Drainpipe not reading correctly the URLs for visual diffs

### ISSUE THREAD

**Issue by beto-aveiga** [Lullabot/drainpipe#625]
When an override file is used for Tugboat config, it may produce URLs for visual diffs that break Tugboat builds.
If there is a way to build these URLs it should be documented. I tried double quotes and scaping them, but it didn't work.

![image](https://github.com/user-attachments/assets/9c3c959c-43bc-449c-b017-5a674e7d1711)

### On Tugboat

![image](https://github.com/user-attachments/assets/de01389a-edbd-4c71-ac7d-a0b57e671260)

### Tags
composer install, .tugboat/config.drainpipe-override.yml, tugboat, visual diffs, visualdiffs

**Comment by mrdavidburns** [comment]
This would be a blocker now that our static tests are checking for uncommitted changes.

**Comment by beto-aveiga** [comment]
> This would be a blocker now that our static tests are checking for uncommitted changes.
I'm not clear about this @mrdavidburns 

I  just think that overriding URLs with parameters for VIsual Diffs doesn't work as expected.

**Comment by mrdavidburns** [comment]
@beto-aveiga Looks like this is the section of code where query parameters are being encoded. Thoughts on how we can fix that?

https://github.com/Lullabot/drainpipe/pull/441/files#diff-fccaa14362cd8508cb094a15287d2e442fc57d94205c6b2146087a552815d1fcR346-R356
```
            // Filter out unsupported config overrides.
            if (!empty($tugboatConfigOverride['php']) && is_array($tugboatConfigOverride['php'])) {
                $tugboatConfigOverride['php'] = array_filter($tugboatConfigOverride['php'], function($key) {
                    return in_array($key, ['aliases', 'urls', 'visualdiff', 'screenshot']);
                }, ARRAY_FILTER_USE_KEY);
                $overrideOutput = [];
                foreach (explode(PHP_EOL, Yaml::dump($tugboatConfigOverride['php'], 2, 2)) as $line) {
                    $overrideOutput[] = str_repeat(' ', 4) . $line;
                }
                $tugboatConfig['overrides']['php'] = rtrim(implode("\n", $overrideOutput));
            }
```

**Comment by beto-aveiga** [comment]
>  Thoughts on how we can fix that?
My first idea is to encode them before or encode them after, and see what happens when I run `composer install`.
However, Xdebugging and seeing the values in real-time would be easier and more effective for discovering new approaches.

Writing a simple test sounds reasonable, too.
