### ISSUE TITLE
Support local composer, or make explicit dependency on `ddev composer`

### ISSUE THREAD

**Issue by hawkeyetwolf** [Lullabot/drainpipe#64]
When running `composer install` rather than `ddev composer install`, I get instructions to execute these user commands:
```
ddev config --additional-hostnames="*."
ddev restart
```
Note the lack of hostname after `*.` (should say `*.project-name`) because of the missing environment variable, `DDEV_SITENAME`:
```
$additionalHostname = '*.' . getenv('DDEV_SITENAME');
```
https://github.com/Lullabot/drainpipe-dev/blob/main/src/DevScaffoldInstallerPlugin.php#L208

Should we just say on the tin that Drainpipe doesn't support running composer outside DDEV, or can we somehow account for this discrepancy gracefully?

**Comment by hawkeyetwolf** [comment]
Technically I guess this issue would be better posed on https://github.com/Lullabot/drainpipe-dev

**Comment by marcoscano** [comment]
Even if not a best practice, nothing really prevents users to run composer on the host, when working on DDEV projects. Also, DDEV is not required for drainpipe, so not sure how best to deal with this gracefully? Check for a `.ddev` folder in the project root?

**Comment by deviantintegral** [comment]
Is this fixed now via https://github.com/Lullabot/drainpipe-dev/blob/main/tasks/test.yml#L221 ?

**Comment by hawkeyetwolf** [comment]
The composer plugin that checks for the hostname was was entirely removed in https://github.com/Lullabot/drainpipe-dev/pull/35, and replaced with just calling the `ddev config` command in https://github.com/Lullabot/drainpipe-dev/blob/main/tasks/test.yml#L234 every time directly in the `test` Task, so yeah, we're good on this issue now. Thanks!
