### ISSUE TITLE
Allow JS destinations to differ from source

### ISSUE THREAD

**Issue by hawkeyetwolf** [Lullabot/drainpipe#95]
Follow-up from #86.

Right now, the javascript metapackage that compiles JS with esbuild does not make use of the destination paths provided via the `DRAINPIPE_JAVASCRIPT` environment variable. The only part of the destination passed to esbuild is the file extension; directory and filename are ignored. The end result is that the compiled asset's directory and filename always match the source file, just with a different extension.

**Comment by deviantintegral** [comment]
Given this hasn't come up again in over a year, I'm closing this feature request. If someone has a current need for this, please feel free to reopen.
