### ISSUE TITLE
Provide a Tugboat template for Pantheon review environments

### ISSUE THREAD

**Issue by deviantintegral** [Lullabot/drainpipe#96]
At our Tugboat BoF at the retreat last week, it was brought up that supporting tugboat would help with spinning up new sites and clients. Let's get something in place that sets up a Tugboat configuration file.

**Comment by deviantintegral** [comment]
@rabbitlair @mrdavidburns is there anything in particular you'd like to see in how this works?

**Comment by deviantintegral** [comment]
I have an in-progress PR for the tugboat image up at https://github.com/TugboatQA/images/pull/102. I'd love to pass this off to @justafish to get finished off.

**Comment by justafish** [comment]
Fixed in #213
